### ISSUE TITLE
Reverse Proxy with Caching | NGINX

### ISSUE THREAD

**Issue by nexusofdoom** [abedra/nginx-auth-token-module#6]
trying to do this 

ref https://github.com/nexusofdoom/lancache-installer/issues/20

they use this it looks like https://learn.akamai.com/en-us/webhelp/adaptive-media-delivery/adaptive-media-delivery-implementation-guide/GUID-041AEFDE-7E25-4AD8-B6C4-73F1B7200F02.html

**Comment by abedra** [comment]
What exactly are you trying to do? Are you using this module? Is there a specific test or feature you are looking for?
